export const departments = ["Продукт", "Технологии", "Операции"];

export const teams = [
  { name: "Платформа", department: "Технологии" },
  { name: "Разработка продукта", department: "Технологии" },
  { name: "Аналитика", department: "Продукт" },
  { name: "HR", department: "Операции" }
];

export const recruiters = ["Рекрутер A", "Рекрутер B", "Рекрутер C", "Рекрутер D"];

export const dataSources = {
  vacancies: "Яндекс Таблицы",
  candidates: "Huntflow",
  offers: "Huntflow"
};

export const vacancies = [
  {
    id: 1,
    title: "Старший разработчик серверной части",
    department: "Технологии",
    team: "Платформа",
    recruiter: "Рекрутер A",
    grade: "Senior",
    targetCloseDays: 45,
    actualCloseDays: 52,
    gradeTargetDays: 45,
    candidateStartDays: 14,
    status: "active",
    daysToClose: 0,
    slaDays: 45,
    isRisk: true,
    riskReason: "Просрочен SLA",
    riskLevel: "high",
    riskLevelLabel: "Высокий"
  },
  {
    id: 2,
    title: "Frontend-разработчик",
    department: "Технологии",
    team: "Разработка продукта",
    recruiter: "Рекрутер A",
    grade: "Middle",
    targetCloseDays: 45,
    actualCloseDays: 38,
    gradeTargetDays: 40,
    candidateStartDays: 10,
    status: "closed",
    daysToClose: 38,
    slaDays: 45,
    isRisk: false,
    riskReason: "",
    riskLevel: "low",
    riskLevelLabel: "Низкий"
  },
  {
    id: 3,
    title: "Продуктовый аналитик",
    department: "Продукт",
    team: "Аналитика",
    recruiter: "Рекрутер B",
    grade: "Middle",
    targetCloseDays: 35,
    actualCloseDays: 39,
    gradeTargetDays: 35,
    candidateStartDays: 12,
    status: "active",
    daysToClose: 0,
    slaDays: 35,
    isRisk: true,
    riskReason: "Низкий поток кандидатов",
    riskLevel: "high",
    riskLevelLabel: "Высокий"
  },
  {
    id: 4,
    title: "Менеджер продукта",
    department: "Продукт",
    team: "Аналитика",
    recruiter: "Рекрутер B",
    grade: "Senior",
    targetCloseDays: 40,
    actualCloseDays: 41,
    gradeTargetDays: 45,
    candidateStartDays: 16,
    status: "closed",
    daysToClose: 41,
    slaDays: 40,
    isRisk: false,
    riskReason: "",
    riskLevel: "low",
    riskLevelLabel: "Низкий"
  },
  {
    id: 5,
    title: "Бизнес-партнер по персоналу",
    department: "Операции",
    team: "HR",
    recruiter: "Рекрутер C",
    grade: "Lead",
    targetCloseDays: 30,
    actualCloseDays: 34,
    gradeTargetDays: 50,
    candidateStartDays: 18,
    status: "active",
    daysToClose: 0,
    slaDays: 30,
    isRisk: true,
    riskReason: "Задержка со стороны нанимающего менеджера",
    riskLevel: "medium",
    riskLevelLabel: "Средний"
  },
  {
    id: 6,
    title: "Специалист по адаптации",
    department: "Операции",
    team: "HR",
    recruiter: "Рекрутер C",
    grade: "Junior",
    targetCloseDays: 30,
    actualCloseDays: 24,
    gradeTargetDays: 30,
    candidateStartDays: 7,
    status: "closed",
    daysToClose: 24,
    slaDays: 30,
    isRisk: false,
    riskReason: "",
    riskLevel: "low",
    riskLevelLabel: "Низкий"
  },
  {
    id: 7,
    title: "Инженер по качеству",
    department: "Технологии",
    team: "Платформа",
    recruiter: "Рекрутер D",
    grade: "Middle",
    targetCloseDays: 40,
    actualCloseDays: 28,
    gradeTargetDays: 35,
    candidateStartDays: 9,
    status: "active",
    daysToClose: 0,
    slaDays: 40,
    isRisk: false,
    riskReason: "",
    riskLevel: "low",
    riskLevelLabel: "Низкий"
  },
  {
    id: 8,
    title: "Системный аналитик",
    department: "Технологии",
    team: "Разработка продукта",
    recruiter: "Рекрутер D",
    grade: "Middle",
    targetCloseDays: 40,
    actualCloseDays: 36,
    gradeTargetDays: 35,
    candidateStartDays: 11,
    status: "closed",
    daysToClose: 36,
    slaDays: 40,
    isRisk: false,
    riskReason: "",
    riskLevel: "low",
    riskLevelLabel: "Низкий"
  }
];

export const candidates = [
  { id: 1, vacancyId: 1, stage: "Отклики", source: "HeadHunter" },
  { id: 2, vacancyId: 1, stage: "Скрининг", source: "HeadHunter" },
  { id: 3, vacancyId: 1, stage: "Интервью", source: "Рекомендации" },
  { id: 4, vacancyId: 1, stage: "Финал", source: "HeadHunter" },
  { id: 5, vacancyId: 1, stage: "Оффер", source: "Рекомендации" },
  { id: 6, vacancyId: 2, stage: "Выход", source: "HeadHunter" },
  { id: 7, vacancyId: 2, stage: "Оффер", source: "HeadHunter" },
  { id: 8, vacancyId: 2, stage: "Финал", source: "Рекомендации" },
  { id: 9, vacancyId: 3, stage: "Отклики", source: "HeadHunter" },
  { id: 10, vacancyId: 3, stage: "Отклики", source: "HeadHunter" },
  { id: 11, vacancyId: 3, stage: "Скрининг", source: "Рекомендации" },
  { id: 12, vacancyId: 3, stage: "Интервью", source: "HeadHunter" },
  { id: 13, vacancyId: 4, stage: "Выход", source: "Карьерный сайт" },
  { id: 14, vacancyId: 4, stage: "Оффер", source: "HeadHunter" },
  { id: 15, vacancyId: 4, stage: "Финал", source: "Рекомендации" },
  { id: 16, vacancyId: 5, stage: "Отклики", source: "HeadHunter" },
  { id: 17, vacancyId: 5, stage: "Скрининг", source: "HeadHunter" },
  { id: 18, vacancyId: 5, stage: "Интервью", source: "Рекомендации" },
  { id: 19, vacancyId: 6, stage: "Выход", source: "HeadHunter" },
  { id: 20, vacancyId: 6, stage: "Оффер", source: "Рекомендации" },
  { id: 21, vacancyId: 7, stage: "Отклики", source: "HeadHunter" },
  { id: 22, vacancyId: 7, stage: "Скрининг", source: "HeadHunter" },
  { id: 23, vacancyId: 7, stage: "Интервью", source: "Рекомендации" },
  { id: 24, vacancyId: 8, stage: "Выход", source: "HeadHunter" },
  { id: 25, vacancyId: 8, stage: "Оффер", source: "HeadHunter" }
];

export const offers = [
  { id: 1, vacancyId: 1, status: "accepted", rejectReason: "", source: "Huntflow" },
  { id: 2, vacancyId: 2, status: "accepted", rejectReason: "", source: "Huntflow" },
  { id: 3, vacancyId: 2, status: "declined", rejectReason: "Компенсация", source: "Huntflow" },
  { id: 4, vacancyId: 4, status: "accepted", rejectReason: "", source: "Huntflow" },
  { id: 5, vacancyId: 4, status: "declined", rejectReason: "Другое предложение", source: "Huntflow" },
  { id: 6, vacancyId: 6, status: "accepted", rejectReason: "", source: "Huntflow" },
  { id: 7, vacancyId: 8, status: "accepted", rejectReason: "", source: "Huntflow" },
  { id: 8, vacancyId: 8, status: "declined", rejectReason: "Сроки выхода", source: "Huntflow" }
];

export const funnelStages = ["Отклики", "Скрининг", "Интервью", "Финал", "Оффер", "Выход"];
